name: Check Accessible Twitch Hosts

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:

jobs:
  check-hosts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run host checker
        run: |
          python -c "
          import requests
          import time
          
          hosts = ['live.twitch.tv', 'video-edge-xxxx.twitch.tv', 'video-weaver.xxxx.hls.ttvnw.net']
          accessible_hosts = []
          
          for host in hosts:
              try:
                  start = time.time()
                  response = requests.get(f'http://{host}', timeout=5)
                  if response.status_code < 400:
                      accessible_hosts.append(host)
                      print(f'✅ {host} is accessible (ping: {round((time.time()-start)*1000)}ms)')
              except Exception as e:
                  print(f'❌ {host} is not accessible: {str(e)}')
                  
          with open('accessible_hosts.txt', 'w') as f:
              f.write('\n'.join(accessible_hosts))
          "

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: accessible-twitch-hosts
          path: accessible_hosts.txt
